"""Type stubs for Flask auth routes."""
from typing import Dict, Optional, Tuple, Any, Union
from flask import Response, Request

#: Flask request object (injected by Flask at runtime)
request: Request  # type: ignore[name-defined]

def jsonify(**kwargs: Any) -> Response: ...
def auth_register() -> Tuple[Response, int]: ...
def auth_login() -> Tuple[Response, int]: ...
def auth_me() -> Union[Tuple[Response, int], Response]: ...
def auth_logout() -> Tuple[Response, int]: ...
